[package]
name = "tile_editor"
version = "1.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
raylib = "5.0.1"
